### ISSUE TITLE
How strictly do we want reproducibility?

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#12] opened 2020-10-04 14:28 UTC
I am working on a hole system proptest, like is used in Cargo. One of the smallest properties I thought of is:

```rust
proptest! {
    #[test]
    fn prop_same_on_repeated_runs(
        (mut solver, cases) in registry_strategy()
    )  {
        for (name, ver) in cases {
            match (solver.run(name, ver), solver.run(name, ver)) {
                (Ok(l), Ok(r)) => assert_eq!(l, r),
                (Err(_), Err(_)) => (), // todo: how to compare Err?
                _ => panic!("not the same result")
            }
        }
    }
}
```
And it is failing, While I work to create a minimal example, I just wanted to be sure this is a test that we want? 
Are there ways we are Ok with there being differences between runs on the same input?

**Comment by mpizenberg** [comment] 2020-10-04 14:36
I think choices of packages not being deterministic makes the order in which versions are picked not the same? I'm not sure. Personally I'd prefer reproducibility over performance. Replacing the default HashMap with one that use seeds in a deterministic way would be better indeed. So that test makes sense to me.

**Comment by Eh2406** [comment] 2020-10-04 15:41
I will continue to make a stand alone test. To fix it we will need to decide which deterministic structure to use. The options I can think of are:

0. Fixed seed. Like using the `fx hash` crate. Pro: full advantage of std's optimizations. Con: the determinism is not otherwise useful.
1. The `indexmap` crate. Pro: insertion order, and can be indexed by that order. Con: not as optimized as std.
2. Ues a `BTree`. Pro: it is sorted so looking at debug representation is nice, and sometimes we can use the sort. And it is std so no dependency.  Con: `O(log(n))` not `O(1)`.

**Comment by aleksator** [comment] 2020-10-04 15:46
Might be worth looking into the original Dart implementation. I believe they are using regular HashMaps.

**Comment by mpizenberg** [comment] 2020-10-04 15:54
I remember reading this article about dropbox rewriting their sync engine in Rust and replacing every non-deterministic part with a deterministic one because of the benefits it gave them: https://dropbox.tech/infrastructure/rewriting-the-heart-of-our-sync-engine.

> The Control thread is designed to be entirely deterministic when its inputs and scheduling decisions are fixed. We use this property to fuzz it with pseudorandom simulation testing. With a seed for our random number generator, we can generate random initial filesystem state, schedules, and system perturbations and let the engine run to completion. Then, if we fail any of our sync correctness checks, we can always reproduce the bug from the original seed. We run millions of scenarios every day in our testing infrastructure.

That seems valuable.

**Comment by aleksator** [comment] 2020-10-04 16:03
I was wrong about Dart's implementation using HashMaps.

They use map initialization like this: `var dependencies = <String, PackageRange>{};`,
which creates _some_ map implementation. I couldn't find a documentation what it was, so I tested it online at https://dartpad.dev/:
```
import 'dart:collection';

void main() {
  var map = <String, String>{};
  print(map is HashMap); // false
  print(map is LinkedHashMap); // true
}
```

LinkedHashMap:
> The insertion order of keys is remembered, and keys are iterated in the order they were inserted into the map.

I guess that's why they don't have any reproducibility issues.

**Comment by Eh2406** [comment] 2020-10-04 16:23
```rust
#[test]
fn same_on_repeated_runs_1() {
    let mut solver = OfflineSolver::<_, NumberVersion>::new();

    solver.add_dependencies(2, NumberVersion(2), vec![]);
    solver.add_dependencies(2, NumberVersion(0), vec![]);

    solver.add_dependencies(
        1,
        NumberVersion(1),
        vec![(2, Range::between(NumberVersion(0), NumberVersion(1)))],
    );
    solver.add_dependencies(1, NumberVersion(0), vec![]);

    solver.add_dependencies(
        0,
        NumberVersion(0),
        vec![(1, Range::any()), (2, Range::any())],
    );

    let name = 0;
    let ver = NumberVersion(0);
    let one = solver.run(name, ver);
    for _ in 0..3 {
        match (&one, &solver.run(name, ver)) {
            (Ok(l), Ok(r)) => assert_eq!(l, r),
            (Err(_), Err(_)) => (), // todo: how to compare Err?
            _ => panic!("not the same result"),
        }
    }
}
```

**Comment by mpizenberg** [comment] 2020-10-04 16:32
Any new `add_dependencies` with the same id replaces the previous one, so those should be equivalent to:
```rust
    solver.add_dependencies(2, NumberVersion(0), vec![]);
    solver.add_dependencies(1, NumberVersion(0), vec![]);
    solver.add_dependencies(
        0,
        NumberVersion(0),
        vec![(1, Range::any()), (2, Range::any())],
    );
```

**Comment by aleksator** [comment] 2020-10-04 16:33
> #[test]
fn same_on_repeated_runs_1() {

_Sometimes_ works! :sweat_smile:
Might be worth increasing the number of runs a bit.

**Comment by mpizenberg** [comment] 2020-10-04 16:52
That's a nice test to show reproducibility problem! I've just changed the types here for readability:
```rust
#[test]
#[rustfmt::skip]
fn same_on_repeated_runs_1() {
    let mut solver = OfflineSolver::<_, NumberVersion>::new();

    solver.add_dependencies("c", 0, vec![]);
    solver.add_dependencies("c", 2, vec![]);
    solver.add_dependencies("b", 0, vec![]);
    solver.add_dependencies("b", 1, vec![("c", Range::between(0, 1))]);

    solver.add_dependencies("a", 0, vec![
        ("b", Range::any()),
        ("c", Range::any()),
    ]);

    let name = "a";
    let ver = NumberVersion(0);
    let one = solver.run(name, ver);
    for _ in 0..3 {
        match (&one, &solver.run(name, ver)) {
            (Ok(l), Ok(r)) => assert_eq!(l, r),
            (Err(_), Err(_)) => (), // todo: how to compare Err?
            _ => panic!("not the same result"),
        }
    }
}
```

**Comment by aleksator** [comment] 2020-10-04 17:54
> 0. Fixed seed. Like using the fx hash crate. Pro: full advantage of std's optimizations. Con: the determinism is not otherwise useful.
> 1. The indexmap crate. Pro: insertion order, and can be indexed by that order. Con: not as optimized as std.
> 2. Ues a BTree. Pro: it is sorted so looking at debug representation is nice, and sometimes we can use the sort. And it is std so no dependency. Con: O(log(n)) not O(1).

@Eh2406 @mpizenberg What are your preferences for these options? I like 1 and 2 more than 0, but choosing between those 2 would probably have to be benchmarked.

**Comment by aleksator** [comment] 2020-10-04 18:05
I've noticed the keys are being removed in `incompatibility.rs` in merge function:
```
    fn merge<T: Clone, F: Fn(&T, &T) -> Option<T>>(
        hashmap_1: &Map<P, T>,
        hashmap_2: &Map<P, T>,
        f: F,
    ) -> Map<P, T> {
```

The documentation for `indexmap` says:
> Preserves insertion order as long as you don't call .remove().

Does it rule out the option of using `indexmap` for us?

**Comment by mpizenberg** [comment] 2020-10-04 19:02
> > 0. Fixed seed. Like using the fx hash crate. Pro: full advantage of std's optimizations. Con: the determinism is not otherwise useful.
> > 1. The indexmap crate. Pro: insertion order, and can be indexed by that order. Con: not as optimized as std.
> > 2. Ues a BTree. Pro: it is sorted so looking at debug representation is nice, and sometimes we can use the sort. And it is std so no dependency. Con: O(log(n)) not O(1).
> 
> @Eh2406 @mpizenberg What are your preferences for these options? I like 1 and 2 more than 0, but choosing between those 2 would probably have to be benchmarked.

I don't have strong opinions on this since I haven't used pubgrub a lot yet and not sure what impact such decision has. From my point of view it is easier to add assumptions than to remove some later. That's why I'd opt for option 0, which doesn't bring any order assumption and fix the determinism issue. It can later easily be replaced by something like 1 or 2.

**Comment by mpizenberg** [comment] 2020-10-04 19:07
> I've noticed the keys are being removed in `incompatibility.rs` in merge function:
> ...
> 
> The documentation for `indexmap` says:
>
> > Preserves insertion order as long as you don't call .remove().
> 
> Does it rule out the option of using `indexmap` for us?

the order of terms in an incompatibility isn't such a problem since it's never used anywhere (the order). Also those rarely contains more than 2 terms so I don't think there is any issue regarding that specifically for usage of `indexmap`.

**Comment by aleksator** [comment] 2020-10-04 20:30
> 0. Fixed seed. Like using the fx hash crate. Pro: full advantage of std's optimizations. Con: the determinism is not otherwise useful.

I can't find anything about using fixed hash in the crate documentation: https://lib.rs/crates/fxhash. It looks like it's just another hashing algorithm implementation that claims to be faster than std's.

**Comment by Eh2406** [comment] 2020-10-04 21:52
I think std's hash map can take its hashing algorithm as an argument.  https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_hasher that `BuildHasher` trate is impled by `FxBuildHasher` in the `fxhash` crate. So `let x: HashMap<K, V, FxBuildHasher> = Default::default();`. `fxhash` is just one option for a non random hashing algorithm, there are many others, it is just the first one to come to mind.

**Comment by mpizenberg** [comment] 2020-10-07 05:35
I'll just close this in favor of #13

**Closed as completed by mpizenberg** 2020-10-07 05:35 UTC

**Comment by aleksator** [comment] 2020-10-07 06:39
> I'll just close this in favor of #13

Usually issues and PRs go hand to hand, since until PR is merged an issue still persists.

There also might be multiple PRs trying to resolve the same issue, like if I submitted all various implementions separately instead of commits that completely override each other in #13.

I get that closing was just for consolidation of discussion in one place though ;)

**Comment by mpizenberg** [comment] 2020-10-07 07:42
yes mostly to have one place of discussion since I mostly see issues as discussions, not bugs, though some are.
